//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greet.DataStructureV4.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Greet.DataStructureV4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a layer in the list on the left.
        /// </summary>
        public static string MapManager_button3_Click_Please_select_a_layer_in_the_list_on_the_left {
            get {
                return ResourceManager.GetString("MapManager_button3_Click_Please_select_a_layer_in_the_list_on_the_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapefiles(*.shp) | *.shp.
        /// </summary>
        public static string MapManager_buttonAdd_Click_Shapefiles___shp______shp {
            get {
                return ResourceManager.GetString("MapManager_buttonAdd_Click_Shapefiles___shp______shp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close wihtout applying changes?.
        /// </summary>
        public static string MapManager_buttonApply_Click_Close_wihtout_applying_changes_ {
            get {
                return ResourceManager.GetString("MapManager_buttonApply_Click_Close_wihtout_applying_changes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifications not saved.
        /// </summary>
        public static string MapManager_buttonApply_Click_Modifications_not_saved {
            get {
                return ResourceManager.GetString("MapManager_buttonApply_Click_Modifications_not_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocomplete.
        /// </summary>
        public static string MapManager_CalculateFrequenciesGridView_Autocomplete {
            get {
                return ResourceManager.GetString("MapManager_CalculateFrequenciesGridView_Autocomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to fill all rows automatically?.
        /// </summary>
        public static string MapManager_CalculateFrequenciesGridView_Try_to_fill_all_rows_automatically_ {
            get {
                return ResourceManager.GetString("MapManager_CalculateFrequenciesGridView_Try_to_fill_all_rows_automatically_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string MapManager_CreateAssocitationTable_Field {
            get {
                return ResourceManager.GetString("MapManager_CreateAssocitationTable_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string MapManager_CreateAssocitationTable_Layer {
            get {
                return ResourceManager.GetString("MapManager_CreateAssocitationTable_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Name.
        /// </summary>
        public static string MapManager_CreateAssocitationTable_Scenario_Name {
            get {
                return ResourceManager.GetString("MapManager_CreateAssocitationTable_Scenario_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string MapManager_CreateAssocitationTable_Value {
            get {
                return ResourceManager.GetString("MapManager_CreateAssocitationTable_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because of duplicate names, some scenarios where not imported to the table.
        /// </summary>
        public static string MapManager_Cs_FormClosing_Because_of_duplicate_names__some_scenarios_where_not_imported_to_the_table {
            get {
                return ResourceManager.GetString("MapManager_Cs_FormClosing_Because_of_duplicate_names__some_scenarios_where_not_im" +
                        "ported_to_the_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading shapefile.
        /// </summary>
        public static string MapManagerCreateScenarios_LoadVertexLayer_Error_while_loading_shapefile {
            get {
                return ResourceManager.GetString("MapManagerCreateScenarios_LoadVertexLayer_Error_while_loading_shapefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or non-existant shapefile filename:.
        /// </summary>
        public static string MapManagerCreateScenarios_LoadVertexLayer_Invalid_or_non_existant_shapefile_filename_ {
            get {
                return ResourceManager.GetString("MapManagerCreateScenarios_LoadVertexLayer_Invalid_or_non_existant_shapefile_filen" +
                        "ame_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        public static string ScenariosControl_buttonExpandCollapse_Click___ {
            get {
                return ResourceManager.GetString("ScenariosControl_buttonExpandCollapse_Click___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Files|*.csv.
        /// </summary>
        public static string ScenariosControl_buttonLoadNewScenario_Click_CSV_Files___csv {
            get {
                return ResourceManager.GetString("ScenariosControl_buttonLoadNewScenario_Click_CSV_Files___csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Scenario File.
        /// </summary>
        public static string ScenariosControl_buttonLoadNewScenario_Click_Select_a_Scenario_File {
            get {
                return ResourceManager.GetString("ScenariosControl_buttonLoadNewScenario_Click_Select_a_Scenario_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pathways, Mix or Vehicle results are beeing recorded..
        /// </summary>
        public static string ScenariosControl_buttonRunAll_Click_No_Pathways__Mix_or_Vehicle_results_are_beeing_recorded_ {
            get {
                return ResourceManager.GetString("ScenariosControl_buttonRunAll_Click_No_Pathways__Mix_or_Vehicle_results_are_beein" +
                        "g_recorded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results are selected to be recorded.
        /// </summary>
        public static string ScenariosControl_buttonRunAll_Click_No_results_are_selected_to_be_recorded {
            get {
                return ResourceManager.GetString("ScenariosControl_buttonRunAll_Click_No_results_are_selected_to_be_recorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open WTP or WTW tabs, after opening a Pathway, Mix or Vehicle right click in the background to select &quot;Values Vector Manager Record This Item&quot;.
        /// </summary>
        public static string ScenariosControl_buttonRunAll_Click_Please_visit_and_select_a_few_in_the_WTP_and_WTW_panes_before_running_simulations_for_all_scenarios {
            get {
                return ResourceManager.GetString("ScenariosControl_buttonRunAll_Click_Please_visit_and_select_a_few_in_the_WTP_and_" +
                        "WTW_panes_before_running_simulations_for_all_scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV:.
        /// </summary>
        public static string ScenariosControl_buttonSave_Click_CSV_ {
            get {
                return ResourceManager.GetString("ScenariosControl_buttonSave_Click_CSV_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV files (*.csv)|*.csv.
        /// </summary>
        public static string ScenariosControl_buttonSave_Click_CSV_files____csv____csv {
            get {
                return ResourceManager.GetString("ScenariosControl_buttonSave_Click_CSV_files____csv____csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Failed.
        /// </summary>
        public static string ScenariosControl_buttonSave_Click_Saving_Failed {
            get {
                return ResourceManager.GetString("ScenariosControl_buttonSave_Click_Saving_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREET Defaults.
        /// </summary>
        public static string ScenariosControl_buttonSetGREETDefaults_Click_GREET_Defaults {
            get {
                return ResourceManager.GetString("ScenariosControl_buttonSetGREETDefaults_Click_GREET_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        public static string ScenariosControl_Collapse___ {
            get {
                return ResourceManager.GetString("ScenariosControl_Collapse___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your Scenario CSV file and Database GREET file to make sure that this ID exists.
        /// </summary>
        public static string ScenariosControl_treeViewResults_NodeMouseDoubleClick_Please_check_your_Scenario_CSV_file_and_Database_GREET_file_to_make_sure_that_this_ID_exists {
            get {
                return ResourceManager.GetString("ScenariosControl_treeViewResults_NodeMouseDoubleClick_Please_check_your_Scenario_" +
                        "CSV_file_and_Database_GREET_file_to_make_sure_that_this_ID_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected result cannot be found in the sets of Mixes, Pathways nor Vehicles.
        /// </summary>
        public static string ScenariosControl_treeViewResults_NodeMouseDoubleClick_The_selected_result_cannot_be_found_in_the_sets_of_Mixes__Pathways_nor_Vehicles {
            get {
                return ResourceManager.GetString("ScenariosControl_treeViewResults_NodeMouseDoubleClick_The_selected_result_cannot_" +
                        "be_found_in_the_sets_of_Mixes__Pathways_nor_Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///  &lt;xs:simpleType name=&quot;ParameterType&quot;&gt;
        ///    &lt;xs:restriction base=&quot;xs:string&quot;&gt;
        ///      &lt;xs:pattern value=&quot;([^;]*);([^;]*);([^;]*);([^;]*);([^;]*);([^;]*);([^;]*);([^;]*);([^;]*);([^;]*)&quot;&gt;&lt;/xs:pattern&gt;
        ///    &lt;/xs:restriction&gt;
        ///  &lt;/xs:simpleType&gt;
        ///  &lt;xs:element name=&quot;greet&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;basic_pa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XMLSchemaV4 {
            get {
                return ResourceManager.GetString("XMLSchemaV4", resourceCulture);
            }
        }
    }
}
