//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greet.UnitLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n              <unitsystem>\r\n              <groups>\r\n              <group name=\"" +
            "distance\" display_name=\"Distance\" format=\"0.000\" unit=\"meters:miles\" mlt=\"0:1:0:" +
            "0\"/>\r\n              <group name=\"area\" display_name=\"Area\" format=\"0.000\" unit=\"" +
            "sq_meters:acres\" mlt=\"0:2:0:0\"/>\r\n              <group name=\"mass\" display_name=" +
            "\"Mass\" format=\"0.000\" unit=\"kilograms:grams\" mlt=\"1:0:0:0\"/>\r\n              <gro" +
            "up name=\"time\" display_name=\"Time\" format=\"0.000\" unit=\"seconds:days\" mlt=\"0:0:1" +
            ":0\"/>\r\n              <group name=\"energy\" display_name=\"Energy\" format=\"0.000\" u" +
            "nit=\"joules:btus\" mlt=\"1:2:-1:0\"/>\r\n              <group name=\"power\" display_na" +
            "me=\"Power\" format=\"0.000\" unit=\"watts:watts\" mlt=\"0:0:0:0\"/>\r\n              <gro" +
            "up name=\"volume\" display_name=\"Volume\" format=\"0.000\" unit=\"cu_meters:gallons\" m" +
            "lt=\"0:3:0:0\"/>\r\n              <group name=\"temperature\" display_name=\"Temperatur" +
            "e\" format=\"0.000\" unit=\"fahrenheit:fahrenheit\" mlt=\"0:0:0:1\"/>\r\n              <g" +
            "roup name=\"percentage\" display_name=\"Percentage\" format=\"0.000\" unit=\"ratio:perc" +
            "ent\" mlt=\"0:0:0:0\"/>\r\n              <group name=\"ratio_group\" display_name=\"Perc" +
            "entage\" format=\"0.000\" unit=\"ratio:ratio\" mlt=\"0:0:0:0\"/>\r\n              <group " +
            "name=\"concentration\" display_name=\"Concentration\" format=\"0.000\" unit=\"parts_per" +
            "_million:parts_per_million\" mlt=\"0:0:0:0\"/>\r\n              <group name=\"unitless" +
            "\" display_name=\"Unitless\" format=\"0.000\" unit=\"unitless:unitless\" mlt=\"0:0:0:0\"/" +
            ">\r\n              <group name=\"currency\" display_name=\"Currency\" format=\"0.000\" u" +
            "nit=\"us_dollar:us_dollar\" mlt=\"0:0:0:0\"/>\r\n              <group name=\"date\" disp" +
            "lay_name=\"Date\" format=\"0\" unit=\"date_year:date_year\" mlt=\"0:0:1:0\"/>\r\n         " +
            "     <group name=\"separative_work\" display_name=\"Separative Work\" format=\"0.000\"" +
            " unit=\"swu:swu\" mlt=\"0:0:0:0\"/>\r\n              <derived name=\"volume_solid_gas\" " +
            "display_name=\"Volume (Solid/Gas)\" format=\"0.000\" base=\"volume:cu_feet\" />\r\n     " +
            "         <derived name=\"efficiency\" display_name=\"Efficiency\" format=\"0.000\" bas" +
            "e=\"percentage:ratio\" />\r\n              <derived name=\"pressure\" display_name=\"Pr" +
            "essure\" format=\"0.000\" base=\"mass:pounds/area:acres\" />\r\n              <derived " +
            "name=\"fuel_consumption\" display_name=\"Fuel Consumption\" format=\"0.000\" base=\"vol" +
            "ume:gallons/distance:miles\" />\r\n              <derived name=\"fuel_economy\" displ" +
            "ay_name=\"Fuel Economy\" format=\"0.000\" base=\"distance:miles/volume:gallons\" />\r\n " +
            "             <derived name=\"energy_intensity\" display_name=\"Energy Intensity\" fo" +
            "rmat=\"0.000\" base=\"energy:btus/distance:miles/mass:short_tons\" />\r\n             " +
            " <derived name=\"heating_value_mass\" display_name=\"Heating Value Mass Basis\" form" +
            "at=\"0.000\" base=\"energy:btus/mass:short_tons\" />\r\n              <derived name=\"h" +
            "eating_value_volume\" display_name=\"Heating Value Volume Basis\" format=\"0.000\" ba" +
            "se=\"energy:btus/volume:gallons\" />\r\n              <derived name=\"density\" displa" +
            "y_name=\"Density\" format=\"0.000\" base=\"mass:grams/volume:cu_feet\" />\r\n           " +
            "   <derived name=\"yield\" display_name=\"Yield\" format=\"0.000\" base=\"mass:pounds\" " +
            "/>\r\n              <derived name=\"acre_yield\" display_name=\"Acre Yield\" format=\"0" +
            ".00\" base=\"mass:short_tons/area:acres\" />\r\n              <derived name=\"corn_yie" +
            "ld\" display_name=\"Corn Yield\" format=\"0.00\" base=\"mass:bushels_corn/area:acres\" " +
            "/>\r\n              <derived name=\"bagasse_yield\" display_name=\"Bagasse Yield\" for" +
            "mat=\"0.00000\" base=\"mass:short_tons/volume:gallons\" />\r\n              <derived n" +
            "ame=\"ethannol_yield\" display_name=\"Ethanol Yield from Sugarcane\" format=\"0.0\" ba" +
            "se=\"volume:gallons/mass:bushels_corn\" />\r\n              <derived name=\"nutrient_" +
            "add\" display_name=\"nutrient additive\" format=\"0.000\" base=\"mass:grams/mass:short" +
            "_tons\" />\r\n              <derived name=\"energy_density\" display_name=\"Energy den" +
            "sity\" format=\"0.000\" base=\"energy:btus/mass:short_tons\" />\r\n              <deriv" +
            "ed name=\"emission_factor\" display_name=\"Emission Factor\" format=\"0.000\" base=\"ma" +
            "ss:grams/energy:mmbtus\" />\r\n              <derived name=\"emission_factor_grams\" " +
            "display_name=\"Emission Factor in Grams\" format=\"0.000\" base=\"mass:grams/mass:kil" +
            "ograms\" />\r\n              <derived name=\"vehicle_emission_factor\" display_name=\"" +
            "Vehicle Emission Factor\" format=\"0.000\" base=\"mass:grams/distance:miles\" />\r\n   " +
            "           <derived name=\"vehicle_energy\" display_name=\"Vehicle Energy Used\" for" +
            "mat=\"0.000\" base=\"energy:btus/distance:miles\" />\r\n              <derived name=\"e" +
            "nergy_use\" display_name=\"Energy Use\" format=\"0.000\" base=\"energy:btus/energy:btu" +
            "s\" />\r\n              <derived name=\"speed\" display_name=\"Speed\" format=\"0.000\" b" +
            "ase=\"distance:miles/time:hours\" />\r\n              <derived name=\"market_value_vo" +
            "lume\" display_name=\"Market Value Volume\" format=\"0.000\" base=\"currency:us_dollar" +
            "/volume:gallons\" />\r\n              <derived name=\"market_value_mass\" display_nam" +
            "e=\"Market Value Mass\" format=\"0.000\" base=\"currency:us_dollar/mass:pounds\" />\r\n " +
            "             <derived name=\"market_value_energy\" display_name=\"Market Value Ener" +
            "gy\" format=\"0.000\" base=\"currency:us_dollar/energy:btus\" />\r\n              <deri" +
            "ved name=\"horsepower_factor\" display_name=\"Horsepower Factor\" format=\"0.000\" bas" +
            "e=\"power:watts/mass:grams\" />\r\n              <derived name=\"loss_rate_per_day\" d" +
            "isplay_name=\"Loss Rate per Day\" format=\"0.000\" base=\"unitless:unitless/time:days" +
            "\" />\r\n              <derived name=\"temp\" display_name=\"\" format=\"\" base=\"energy:" +
            "joules/mass:kilograms/distance:meters\" />\r\n              </groups>\r\n            " +
            "  <units>\r\n              <unit name=\"miles\" display_name=\"Miles\" abbrev=\"mi\" toD" +
            "efault=\"val*1609.344\" fromDefault=\"val/1609.344\" group=\"distance\" />\r\n          " +
            "    <unit name=\"feet\" display_name=\"Feet\" abbrev=\"ft\" toDefault=\"val*0.3048\" fro" +
            "mDefault=\"val/0.3048\" group=\"distance\" />\r\n              <unit name=\"inches\" dis" +
            "play_name=\"Inches\" abbrev=\"in\" toDefault=\"val*0.0254\" fromDefault=\"val/0.0254\" g" +
            "roup=\"distance\" />\r\n              <unit name=\"meters\" display_name=\"Meters\" abbr" +
            "ev=\"m\" toDefault=\"val\" fromDefault=\"val\" group=\"distance\" prefix_serie=\"4\" />\r\n " +
            "             <unit name=\"hecto-kilo-meters\" display_name=\"Hecto Kilo Meters\" abb" +
            "rev=\"100Km\" toDefault=\"val*100000\" fromDefault=\"val/100000\" group=\"distance\" />\r" +
            "\n              <unit name=\"nautical_miles\" display_name=\"Nautical Miles\" abbrev=" +
            "\"nmi\" toDefault=\"val*1852\" fromDefault=\"val/1852\" group=\"distance\" />\r\n         " +
            "     <unit name=\"acres\" display_name=\"Acres\" abbrev=\"ac\" toDefault=\"val*4046.856" +
            "4224\" fromDefault=\"val/4046.8564224\" group=\"area\" />\r\n              <unit name=\"" +
            "sq_miles\" display_name=\"sq Miles\" abbrev=\"mi2\" toDefault=\"val*2589988.110336\" fr" +
            "omDefault=\"val/2589988.110336\" group=\"area\" />\r\n              <unit name=\"sq_kil" +
            "ometers\" display_name=\"sq Kilometers\" abbrev=\"km2\" toDefault=\"val*1000000\" fromD" +
            "efault=\"val/1000000\" group=\"area\" />\r\n              <unit name=\"sq_meters\" displ" +
            "ay_name=\"sq Meters\" abbrev=\"m2\" toDefault=\"val\" fromDefault=\"val\" group=\"area\" /" +
            ">\r\n              <unit name=\"hectares\" display_name=\"Hectares\" abbrev=\"Ha\" toDef" +
            "ault=\"val*10000\" fromDefault=\"val/1000000\" group=\"area\" />\r\n              <unit " +
            "name=\"sq_feet\" display_name=\"sq Feet\" abbrev=\"ft2\" toDefault=\"val*0.09290304\" fr" +
            "omDefault=\"val/0.09290304\" group=\"area\" />\r\n              <unit name=\"sq_inches\"" +
            " display_name=\"sq Inches\" abbrev=\"in2\" toDefault=\"val*0.0064516\" fromDefault=\"va" +
            "l/0.0064516\" group=\"area\" />\r\n              <unit name=\"grams\" display_name=\"Gra" +
            "ms\" abbrev=\"g\" toDefault=\"val/1000\" fromDefault=\"val*1000\" group=\"mass\" prefix_s" +
            "erie=\"3\" above_unit=\"Tonnes\" />\r\n              <unit name=\"kilograms\" display_na" +
            "me=\"Kilograms\" abbrev=\"kg\" toDefault=\"val\" fromDefault=\"val\" group=\"mass\" />\r\n  " +
            "            <unit name=\"short_tons\" display_name=\"Short Tons\" abbrev=\"ton\" toDef" +
            "ault=\"val*907.18474\" fromDefault=\"val/907.18474\" group=\"mass\" />\r\n              " +
            "<unit name=\"long_tons\" display_name=\"Long Tons\" abbrev=\"LT\" toDefault=\"val*1016." +
            "0469088\" fromDefault=\"val/1016.0469088\" group=\"mass\" />\r\n              <unit nam" +
            "e=\"pounds\" display_name=\"Pounds\" abbrev=\"lb\" toDefault=\"val*0.45359237\" fromDefa" +
            "ult=\"val/0.45359237\" group=\"mass\" />\r\n              <unit name=\"tonnes\" display_" +
            "name=\"Tonnes\" abbrev=\"t\" toDefault=\"val*1000\" fromDefault=\"val/1000\" group=\"mass" +
            "\" />\r\n              <unit name=\"bushels_corn\" display_name=\"Bushels Of Corn\" abb" +
            "rev=\"us bsh corn\" toDefault=\"val*25.401\" fromDefault=\"val/25.401\" group=\"mass\" /" +
            ">\r\n              <unit name=\"seconds\" display_name=\"Seconds\" abbrev=\"sec\" toDefa" +
            "ult=\"val\" fromDefault=\"val\" group=\"time\" above_unit=\"Minutes\" />\r\n              " +
            "<unit name=\"minutes\" display_name=\"Minutes\" abbrev=\"min\" toDefault=\"val*60\" from" +
            "Default=\"val/60\" group=\"time\" above_unit=\"Hours\" below_unit=\"Hours\" />\r\n        " +
            "      <unit name=\"hours\" display_name=\"Hours\" abbrev=\"hr\" toDefault=\"val*3600\" f" +
            "romDefault=\"val/3600\" group=\"time\" above_unit=\"Days\" below_unit=\"Days\" />\r\n     " +
            "         <unit name=\"days\" display_name=\"Days\" abbrev=\"days\" toDefault=\"val*8640" +
            "0\" fromDefault=\"val/86400\" group=\"time\" above_unit=\"Years\" below_unit=\"Years\" />" +
            "\r\n              <unit name=\"years\" display_name=\"Years\" abbrev=\"yr\" toDefault=\"v" +
            "al*31556926\" fromDefault=\"val/31556926\" group=\"time\" />\r\n              <unit nam" +
            "e=\"date_year\" display_name=\"Year\" abbrev=\"\" toDefault=\"val\" fromDefault=\"val\" gr" +
            "oup=\"date\" />\r\n              <unit name=\"btus\" display_name=\"Btus\" abbrev=\"btu\" " +
            "toDefault=\"val*1055.05585262\" fromDefault=\"val/1055.05585262\" group=\"energy\" pre" +
            "fix_serie=\"2\" />\r\n              <unit name=\"mmbtus\" display_name=\"mmBtus\" abbrev" +
            "=\"mmbtu\" toDefault=\"val*1055055852.62\" fromDefault=\"val/1055055852.62\" group=\"en" +
            "ergy\" />\r\n              <unit name=\"joules\" display_name=\"Joules\" abbrev=\"J\" toD" +
            "efault=\"val\" fromDefault=\"val\" group=\"energy\" prefix_serie=\"1\" />\r\n             " +
            " <unit name=\"mega-joules\" display_name=\"MJoules\" abbrev=\"MJ\" toDefault=\"val*1000" +
            "000\" fromDefault=\"val/1000000\" group=\"energy\" />\r\n              <unit name=\"tonn" +
            "e_of_oil_equivalent\" display_name=\"Tonne of Oil Equivalent\" abbrev=\"toe\" toDefau" +
            "lt=\"val*44769000000\" fromDefault=\"val/44769000000\" group=\"energy\" />\r\n          " +
            "    <unit name=\"watt_hours\" display_name=\"Watt Hours\" abbrev=\"Wh\" toDefault=\"val" +
            "*3600\" fromDefault=\"val/3600\" group=\"energy\" prefix_serie=\"1\" />\r\n              " +
            "<unit name=\"horsepower_hours\" display_name=\"Horsepower Hours\" abbrev=\"hph\" toDef" +
            "ault=\"val*2684519.537696173\" fromDefault=\"val/2684519.537696173\" group=\"energy\" " +
            "/>\r\n              <unit name=\"calories\" display_name=\"Calories\" abbrev=\"cal\" toD" +
            "efault=\"val*4.184\" fromDefault=\"val/4.184\" group=\"energy\" />\r\n              <uni" +
            "t name=\"kilocalories\" display_name=\"Kilocalories\" abbrev=\"kilocal\" toDefault=\"va" +
            "l*4184\" fromDefault=\"val/4184\" group=\"energy\" />\r\n              <unit name=\"watt" +
            "s\" display_name=\"Watts\" abbrev=\"W\" toDefault=\"val\" fromDefault=\"val\" group=\"powe" +
            "r\" prefix_serie=\"1\" />\r\n              <unit name=\"horsepower\" display_name=\"Metr" +
            "ic Horsepower\" abbrev=\"hp\" toDefault=\"val*735.49875\" fromDefault=\"val/735.49875\"" +
            " group=\"power\" />\r\n              <unit name=\"gallons\" display_name=\"Gallons\" abb" +
            "rev=\"gal\" toDefault=\"val*0.003785411784 \" fromDefault=\"val/0.003785411784 \" grou" +
            "p=\"volume\" />\r\n              <unit name=\"liters\" display_name=\"Liters\" abbrev=\"L" +
            "\" toDefault=\"val/1000\" fromDefault=\"val*1000\" group=\"volume\" />\r\n              <" +
            "unit name=\"cu_feet\" display_name=\"cu Feet\" abbrev=\"ft3\" toDefault=\"val*0.0283168" +
            "46592\" fromDefault=\"val/0.028316846592\" group=\"volume\" />\r\n              <unit n" +
            "ame=\"cu_meters\" display_name=\"cu Meters\" abbrev=\"m3\" toDefault=\"val\" fromDefault" +
            "=\"val\" group=\"volume\" />\r\n              <unit name=\"cu_centimeters\" display_name" +
            "=\"cu Centimeters\" abbrev=\"cm3\" toDefault=\"val*.000001\" fromDefault=\"val/.000001\"" +
            " group=\"volume\" />\r\n              <unit name=\"oil_barrel\" display_name=\"Oil Barr" +
            "el\" abbrev=\"bba\" toDefault=\"val*0.158987294928\" fromDefault=\"val/0.158987294928\"" +
            " group=\"volume\" />\r\n              <unit name=\"bushels\" display_name=\"Bushels as " +
            "Volume\" abbrev=\"us bshv\" toDefault=\"val*0.03523907016688\" fromDefault=\"val/0.035" +
            "23907016688\" group=\"volume\" />\r\n              <unit name=\"fahrenheit\" display_na" +
            "me=\"Fahrenheit\" abbrev=\"F\" toDefault=\"val\" fromDefault=\"val\" group=\"temperature\"" +
            " />\r\n              <unit name=\"celsius\" display_name=\"Celsius\" abbrev=\"C\" toDefa" +
            "ult=\"9/5*val+32\" fromDefault=\"5/9*(val-32)\" group=\"temperature\" />\r\n            " +
            "  <unit name=\"kelvin\" display_name=\"Kelvin\" abbrev=\"K\" toDefault=\"val*9/5-459.67" +
            "\" fromDefault=\"(val+459.67)*5/9\" group=\"temperature\" />\r\n              <unit nam" +
            "e=\"rankine\" display_name=\"Rankine\" abbrev=\"R\" toDefault=\"val-459.67\" fromDefault" +
            "=\"val+459.67\" group=\"temperature\" />\r\n              <unit name=\"ratio\" display_n" +
            "ame=\"Ratio\" abbrev=\"\" toDefault=\"val\" fromDefault=\"val\" group=\"percentage\" />\r\n " +
            "             <unit name=\"percent\" display_name=\"Percent\" abbrev=\"%\" toDefault=\"v" +
            "al/100\" fromDefault=\"val*100\" group=\"percentage\" />\r\n              <unit name=\"p" +
            "arts_per_million\" display_name=\"Parts per Million\" abbrev=\"ppm\" toDefault=\"val\" " +
            "fromDefault=\"val\" group=\"concentration\" />\r\n              <unit name=\"mlt\" displ" +
            "ay_name=\"MLT\" abbrev=\"MLT\" toDefault=\"val/.000006\" fromDefault=\"val*.000006\" gro" +
            "up=\"concentration\" />\r\n              <unit name=\"unitless\" display_name=\"Unitles" +
            "s\" abbrev=\"\" toDefault=\"val\" fromDefault=\"val\" group=\"unitless\" />\r\n            " +
            "  <unit name=\"us_dollar\" display_name=\"US Dollar\" abbrev=\"$\" toDefault=\"val\" fro" +
            "mDefault=\"val\" group=\"currency\" />\r\n              <unit name=\"us_cent\" display_n" +
            "ame=\"US Cent\" abbrev=\"c\" toDefault=\"val/100\" fromDefault=\"100*val\" group=\"curren" +
            "cy\" />\r\n              <unit name=\"swu\" display_name=\"Separative work units\" abbr" +
            "ev=\"swu\" toDefault=\"val\" fromDefault=\"val\" group=\"separative_work\" />\r\n         " +
            "     <unit name=\"us_bsh_soybean\" display_name=\"\" abbrev=\"dry bsh sb\" toDefault=\"" +
            "val*23.68\" fromDefault=\"val/23.68\" group=\"mass\" customUnit=\"True\" />\r\n          " +
            "    </units>\r\n              <prefixes>\r\n              <serie id=\"1\">\r\n          " +
            "    <prefix abbrev=\"G\" power=\"9\" />\r\n              <prefix abbrev=\"M\" power=\"6\" " +
            "/>\r\n              <prefix abbrev=\"k\" power=\"3\" />\r\n              <prefix abbrev=" +
            "\"m\" power=\"-3\" />\r\n              <prefix abbrev=\"u\" power=\"-6\" />\r\n             " +
            " <prefix abbrev=\"n\" power=\"-9\" />\r\n              </serie>\r\n              <serie " +
            "id=\"2\">\r\n              <prefix abbrev=\"mm\" power=\"6\" />\r\n              </serie>\r" +
            "\n              <serie id=\"3\">\r\n              <prefix abbrev=\"k\" power=\"3\" />\r\n  " +
            "            <prefix abbrev=\"m\" power=\"-3\" />\r\n              <prefix abbrev=\"u\" p" +
            "ower=\"-6\" />\r\n              </serie>\r\n              <serie id=\"4\">\r\n            " +
            "  <prefix abbrev=\"k\" power=\"3\" />\r\n              </serie>\r\n              </prefi" +
            "xes>\r\n              </unitsystem>\r\n            ")]
        public string Units {
            get {
                return ((string)(this["Units"]));
            }
            set {
                this["Units"] = value;
            }
        }
    }
}
